language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot

branches:
  only:
  - master

# Travis is running Ubuntu 12.04 which doesn't have package libbase58-dev
before_install:
  - wget https://github.com/bitcoin/libbase58/archive/v0.1.4.tar.gz -O libbase58-0.1.4.tar.gz
  - tar -xzf libbase58-0.1.4.tar.gz
  - pushd libbase58-0.1.4 && autoreconf --install && ./configure --prefix=/usr && make && sudo make install && popd

install:
  - phpize
  - ./configure
  - make

before_script:
  make install

script:
  make test

